# Generated by Django 4.2.4 on 2023-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_photo_album_remove_photo_message_and_more'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='post_photo', to='album.photo'),
        ),
    ]
