# Generated by Django 4.2.4 on 2023-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('chat', '0004_alter_message_date_change_alter_message_date_create'),
        ('album', '0002_album_avatar_album_alter_photo_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='photo', to='album.album'),
        ),
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='photo', to='chat.message'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='photo', to='post.post'),
        ),
    ]
