# Generated by Django 4.2.4 on 2023-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_photo_album_remove_photo_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='album_photo', to='album.photo'),
        ),
    ]
