version: '3.8'

services:


  backend:
    container_name: backend2
    build: ../backend/Social_network
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic
      && gunicorn Social_network.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - '8000:8000'
    env_file:
      - ../.env
    environment:
      - ENV=$ENV_PROD
    depends_on:
      - redis
      - db

  frontend:
    container_name: frontend
    build: ..
    restart: unless-stopped
    volumes:
      - ./deployment/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - '80:80'
    depends_on:
      - backend


  db:
    container_name: db2
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_DB=$NAME


  celery_worker_for_db:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q task_db --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/

      # для доступа к базе при отправке email
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  celery_worker_photos:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q photos --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  celery_worker_for_email:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q email --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  celery_worker_test:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q test_task --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  celery_worker_task_1:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q task_1 --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  celery_worker_task_2:
    build: ../backend/Social_network
    command: celery --app=tasks worker -Q task_2 --loglevel=INFO
    volumes:
      - ./backend/Social_network:/usr/src/app/
    env_file:
      - ../.env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7.2-alpine

    # для доступа к базе при отправке email
    env_file:
      - ../.env

  celery-flower:
    build: ../backend/Social_network
    command: celery flower -A tasks --port=5556 --broker=redis://redis:6379/0
    ports:
      - '5556:5556'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - celery_worker_for_email
      - celery_worker_for_db
      - celery_worker_task_1
      - celery_worker_task_2

  celery-beat:
    build: ../backend/Social_network
    command: celery -A tasks beat --loglevel=INFO
    volumes:
      - ./project/:/usr/src/app/
    depends_on:
      - redis
volumes:
  postgres_data:
  static_value:
  media_value:

