# Generated by Django 4.2.4 on 2023-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date_change_alter_message_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
