# Generated by Django 4.2.4 on 2023-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_photo_album_remove_photo_message_and_more'),
        ('chat', '0004_alter_message_date_change_alter_message_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photo_message', to='album.photo'),
        ),
    ]
