# Generated by Django 4.2.4 on 2023-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
