# Generated by Django 4.2.4 on 2023-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
