# Generated by Django 4.2.4 on 2023-09-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_education_date_graduation_alter_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_stop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
